### PR TITLE
fix: Do not remove cilium_vxlan interface. Ask the user instead

### LINKED ISSUE #1495: Cilium can break when re-enabling load-balancer
### Summary

Looks like changing any value on the load-balancer forces an update on the rest of the helm charts

```bash
# sudo k8s helm list -A
NAME                   	NAMESPACE     	REVISION	UPDATED                                	STATUS  	CHART                	APP VERSION
ck-dns                 	kube-system   	106     	2025-06-03 22:40:10.749583778 +0000 UTC	deployed	coredns-1.36.0       	1.11.3
ck-network             	kube-system   	173     	2025-06-03 22:41:20.100130652 +0000 UTC	deployed	cilium-1.16.3        	1.16.3
ck-storage             	kube-system   	106     	2025-06-03 22:40:09.82243214 +0000 UTC 	deployed	rawfile-csi-0.9.0    	0.8.0
gpu-operator-1748041414	gpu-operator  	1       	2025-05-23 23:03:37.473755314 +0000 UTC	deployed	gpu-operator-v24.9.2 	v24.9.2
metallb                	metallb-system	4       	2025-06-03 22:49:57.492344165 +0000 UTC	deployed	metallb-0.14.8       	v0.14.8
metallb-loadbalancer   	metallb-system	4       	2025-06-03 22:50:00.44377732 +0000 UTC 	deployed	ck-loadbalancer-0.1.1	0.1.1
metrics-server         	kube-system   	106     	2025-06-03 22:40:10.741188861 +0000 UTC	deployed	metrics-server-3.12.2	0.7.2
```

Somehow the change of enabling and disabling load-balancer sometimes breaks one of the pods in the Cilium cluster
```bash
# ubuntu@juju-8966e0-1-lxd-3:~$ kubectl -n kube-system exec -it ds/cilium -- cilium status
Defaulted container "cilium-agent" out of: cilium-agent, config (init), mount-cgroup (init), apply-sysctl-overwrites (init), mount-bpf-fs (init), clean-cilium-state (init), install-cni-binaries (init)
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.32 (v1.32.3) [linux/amd64]
Kubernetes APIs:         ["EndpointSliceOrEndpoint", "cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumEndpoint", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumCIDRGroup", "core/v1::Namespace", "core/v1::Pods", "core/v1::Service", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    False
Host firewall:           Disabled
SRv6:                    Disabled
CNI Chaining:            none
CNI Config file:         successfully wrote CNI configuration file to /host/etc/cni/net.d/05-cilium.conflist
Cilium:                  Ok   1.16.3 (v1.16.3-f221719170)
NodeMonitor:             Listening for events on 64 CPUs with 64x4096 of shared memory
Cilium health daemon:    Ok
IPAM:                    IPv4: 4/254 allocated from 10.1.1.0/24,
IPv4 BIG TCP:            Disabled
IPv6 BIG TCP:            Disabled
BandwidthManager:        Disabled
Routing:                 Network: Tunnel [vxlan]   Host: Legacy
Attach Mode:             Legacy TC
Device Mode:             veth
Masquerading:            IPTables [IPv4: Enabled, IPv6: Disabled]
Controller Status:       31/31 healthy
Proxy Status:            OK, ip 10.1.1.12, 0 redirects active on ports 10000-20000, Envoy: embedded
Global Identity Range:   min 256, max 65535
Hubble:                  Ok              Current/Max Flows: 4095/4095 (100.00%), Flows/s: 10.58   Metrics: Disabled
Encryption:              Disabled
Cluster health:          7/8 reachable   (2025-06-03T22:44:08Z)
  Name                   IP              Node        Endpoints
  juju-8966e0-1-lxd-3    10.0.120.206    reachable   unreachable
Modules Health:          Stopped(0) Degraded(0) OK(52)
```

### What Should Happen Instead?

Calico network should not break because of a change in load-balancer
Ideally all helm charts should not be uptadate if just metallb changes

### Reproduction Steps

The way I have seen it reproducible is
1. Deploy k8s and k8s-worker (unsure if this is a must)
2. Enable load-balancer
3. Disable load-balancer
4. Enable load-balancer
5. Check k8s status
```bash
# sudo k8s status
cluster status:           ready
control plane nodes:      10.0.120.206:6400 (voter), 10.0.120.208:6400 (voter), 10.0.120.207:6400 (voter)
high availability:        yes
datastore:                k8s-dqlite
network:                  enabled
dns:                      enabled at 10.152.183.119
ingress:                  disabled
load-balancer:            Failed to deploy MetalLB, the error was: failed to enable LoadBalancer: failed to apply MetalLB LoadBalancer configuration: failed to install metallb-loadbalancer: 1 error occurred:
	* Internal error occurred: failed calling webhook "ipaddresspoolvalidationwebhook.metallb.io": failed to call webhook: Post "https://metallb-webhook-service.metallb-system.svc:443/validate-metallb-io-v1beta1-ipaddresspool?timeout=10s": dial tcp 10.152.183.228:443: connect: operation not permitted


local-storage:            enabled at /var/snap/k8s/common/rawfile-storage
gateway                   disabled
```

6. Check cilium status
```bash
# ubuntu@juju-8966e0-1-lxd-3:~$ kubectl -n kube-system exec -it ds/cilium -- cilium status
[..]
Cluster health:          7/8 reachable   (2025-06-03T22:44:08Z)
  Name                   IP              Node        Endpoints
  juju-8966e0-1-lxd-3    10.0.120.206    reachable   unreachable
Modules Health:          Stopped(0) Degraded(0) OK(52)
```

### System information

Baremetal MAAS 3.5/stable
Canonical Kubernetes 1.32/candidate revision 858 from 2025_05_21 (Needed it because of https://github.com/canonical/k8s-operator/issues/437)

### Can you suggest a fix?

_No response_

### Are you interested in contributing with a fix?

_No response_

### LINKED ISSUE #1585: timed out during opening handshake when adding a second node
### Summary

Mirrored from: https://bugs.launchpad.net/snap-openstack/+bug/2115170
Similar with: https://github.com/canonical/k8s-snap/issues/1495

openstack 2024.1 742 2024.1/edge canonical** -
k8s   v1.32.5  3723  latest/stable  canonical✓  classic,held

Sunbeam deployment with the local multi-node scenario fails at the step of adding the second node to the cluster as "Error: timed out during opening handshake" is returned.

```bash
+ ssh sunbeam-multi-node-2 -t -- 'cat '\''sunbeam-multi-node-2.asc'\'' | sunbeam cluster join --role control,compute,storage -'
An unexpected error has occurred. Please see https://canonical-openstack.readthedocs-hosted.com/en/latest/how-to/troubleshooting/inspecting-the-cluster/ for troubleshooting information.
Error: timed out during opening handshake

+ sunbeam cluster list
                       openstack-machines
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┓
┃ Node ┃ Machine ┃ Compute ┃ Control ┃ Storage ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━┩
│ 10.100.70.1 │ running │ active │ active │ active │
│ sunbeam-multi-node-2 │ running │ │ active │ │
└──────────────────────┴─────────┴─────────┴─────────┴─────────┘
```

`192.168.124.131:17070` is the Juju controller running on K8s and behind MetalLB.

```
03:37:07,677 root DEBUG Cannot access endpoint ('192.168.124.131:17070', '-----BEGIN CERTIFICATE-----\nMIIEEzCCAnugAwIBAgIVAO/2jA7AHZ7MYZVqAN4D8NXrIxfBMA0GCSqGSIb3DQEB\nCwUAMCExDTALBgNVBAoTBEp1anUxEDAOBgNVBAMTB2p1anUtY2EwHhcNMjUwNjIz\nMDI1MDU0WhcNMzUwNjIzMDI1NTU0WjAhMQ0wCwYDVQQKEwRKdWp1MRAwDgYDVQQD\nEwdqdWp1LWNhMIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAr8CSP+rr\nmbat6C6sCd2Yz9vr2a7gXbIfmjJ9pPSbcmQ3aapwanWAnmAoSgV+a9L+wHnDN2XY\n7ZK2fif3qAVVK5OZwABEILnknZ4pDJOv4TMHTR+X1mba4rtv31wlFOrjQLBIWqit\nTk1Wmf9riezo59gyACU2LuXO4/UligVnQK5Y+QhPYuEqnWWuZCXwSlzjxC8nQMDq\nUy2FSo4kb+TZDsm/GcqtOKvvzIDF8H/0DOpZWa6HJgaVW3ZPdZFxqRQ0namVKtA9\nFijCBssKYgU8QqCi4NzgegW/qkR9J/NtQBWt0byZn/p3zRNIpFmjNtsR3lkZwzZ8\nEpORxTlsxXfmYj+kRLhRvrCo3Fy342upyo5P3IyRk+rb9pxQ36SQDfFZabEHzGWO\nCDH/C3HrNpDn2qG9rBv5GanXfTyU4z75DjjFNGIyuTu9aidatuWGaa11FRlxeOfh\nyNH2Y98lzkDSTtV/iK16VkLYtBCDrtNNsiCssicQQ66a1qumQHr20L1LAgMBAAGj\nQjBAMA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRw\nIgJwFaxdjW5z6L1nWkGzMQPFjzANBgkqhkiG9w0BAQsFAAOCAYEAVQezsZDQuGJA\n7FqfNC6+aWMU41jsIERk7s9FUUk5G9GXdIfQDXcCU0PIjC3D34fQhep5AFW3xUoP\nX42CCUjkjP34VD6cwdGCz3/4PDfkO/5jqRQwGcFLSiKygu3HTX5gKS+Plk9TLjFk\nT+T+TAREgO5uLrPF7VEVqbuD0mrmPnBtFk7W6WtcZqlWDJua7+fpBVBKBeNgO/Xt\nYjlnnLvWrRESVxjS02RcwOBzzC1++RI98clwCH1wrAZ08pSbO5/05dNyHjQowLA4\nBEKiS0p6cbieF/f+KHuFCXXTVJifXxHCEuRcGenI/PTOmBdJDDT8jCvkUyhhqr3B\ngn4o6ofugEwbnrwTBT2JuiYvW4QwUrQSF39sNJmaKVanQmr6LTWtYnaAnBoQstdb\nTPpzTN5JswtlW4YSHqlkCMuCJYS0R32tHh+Zd9CfeCpl8692ir8xRWsemMb+Unhg\nDbc4RfODHf5WQoy//5ldkZudI+yLWXItXU/Ix5OIHwwSEeRwbWfR\n-----END CERTIFICATE-----\n'): None
03:37:07,679 sunbeam.utils DEBUG timed out during opening handshake
Traceback (most recent call last):
  File "/snap/openstack/742/lib/python3.12/site-packages/websockets/asyncio/client.py", line 541, in __await_impl__
    self.connection = await self.create_connection()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/snap/openstack/742/lib/python3.12/site-packages/websockets/asyncio/client.py", line 467, in create_connection
    _, connection = await loop.create_connection(factory, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/snap/openstack/742/lib/python3.12/site-packages/websockets/asyncio/client.py", line 539, in __await_impl__
    async with asyncio_timeout(self.open_timeout):
  File "/usr/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
```

But looking at the packet dump, it looks like the second host tries to send the traffic over the `cilium_vxlan ` interface. The node-2 has it but node-1 doesn't have the `cilium_vxlan` interface.

```bash
sunbeam-multi-node-2:~$ ip -br a
lo               UNKNOWN        127.0.0.1/8 ::1/128 
enp1s0           UP             192.168.124.32/24 fe80::5054:ff:fe10:5ada/64 
enp9s0           UP             fe80::5054:ff:fe28:f46f/64 
cilium_net@cilium_host UP             fe80::40a1:1cff:fe60:e06b/64 
cilium_host@cilium_net UP             10.1.1.127/32 fe80::a060:ceff:fed7:9558/64 
cilium_vxlan     UNKNOWN        fe80::45c:55ff:fed2:b8c7/64 
lxc_health@if7   UP             fe80::244f:bcff:fe7d:fe91/64 
lxcc2b7386e9b73@if9 UP             fe80::a02c:32ff:fec6:2364/64 
lxcdc7917415599@if13 UP             fe80::48a3:18ff:fe7e:ce6/64 
```

```bash
sunbeam-multi-node-1:~$ ip -br a
lo               UNKNOWN        127.0.0.1/8 ::1/128 
enp1s0           UP             192.168.124.31/24 fe80::5054:ff:fe5b:2426/64 
enp9s0           UP             fe80::5054:ff:fe8a:68ed/64 
cilium_net@cilium_host UP             fe80::f407:c2ff:fefc:ad57/64 
cilium_host@cilium_net UP             10.1.0.10/32 fe80::c0fc:e3ff:fe80:b1c0/64 
lxc_health@if10  UP             fe80::74f8:6bff:fe24:e4b0/64 
lxc03bd15b17807@if12 UP             fe80::e01d:a7ff:fec0:20c1/64 
lxc38ba57bb18eb@if14 UP             fe80::8835:3eff:fee2:85a2/64 
lxcdee0e40af2b0@if18 UP             fe80::cf6:63ff:fe2e:88cb/64 
lxcde5d8c3511e6@if20 UP             fe80::80a4:46ff:fe5a:6e98/64 
lxc51ca5ac721da@if22 UP             fe80::1015:e0ff:fe45:48f5/64 
lxc49934d74ab03@if28 UP             fe80::cc9b:a8ff:fec1:ac44/64 
lxcd4b989f25ccf@if30 UP             fe80::2843:d2ff:fefc:d6f3/64 
lxcfdad5bebdb51@if32 UP             fe80::d018:5aff:fe16:84e6/64 
lxc9e6af1d00da4@if34 UP             fe80::28d2:c2ff:fed3:a4e7/64 
lxceb53bf452a9f@if36 UP             fe80::30b7:29ff:fe04:1230/64 
lxcdb6001dd41a1@if38 UP             fe80::f89e:55ff:fe19:b425/64 
lxcdf8c81fadac2@if40 UP             fe80::24db:80ff:fe3c:4594/64 
lxc935407aab37b@if42 UP             fe80::6806:7fff:fe8e:8132/64 
lxcce905f98e813@if44 UP             fe80::b8b1:71ff:fe29:cc95/64 
lxcc430fd8dc4e8@if46 UP             fe80::f43b:d7ff:fe0f:67e6/64 
lxc3ced81c64e0a@if48 UP             fe80::b8f9:77ff:fe64:2fcc/64 
lxcb42522b9262d@if50 UP             fe80::60b3:95ff:fe21:640b/64 
lxcc643b982084a@if52 UP             fe80::3cf2:a5ff:feda:bcda/64 
lxcd6ce8269d949@if54 UP             fe80::b0db:6ff:fe7c:74c2/64 
lxc30c043a8a327@if56 UP             fe80::b06b:bdff:fec8:6a50/64 
lxcf3c84ac09b41@if58 UP             fe80::cc31:30ff:fe76:d0d4/64 
lxca719c07d88a9@if60 UP             fe80::20ce:f5ff:fe4d:a6ec/64 
lxc57d94ccdaab3@if62 UP             fe80::d86d:7bff:fe06:cd38/64 
lxc31b02b8a50c8@if64 UP             fe80::ecd4:d8ff:feb9:c5e1/64 
lxcb6e785f9e64e@if66 UP             fe80::cc68:95ff:feb1:7197/64 
lxccab50956554a@if68 UP             fe80::4ce5:fbff:fec3:c0cf/64 
lxc4c53e30e690e@if70 UP             fe80::c076:25ff:fe0a:54c4/64 
lxc26965f7fd42a@if72 UP             fe80::183d:4fff:fe0f:d13e/64 
lxc9faeb62452c0@if74 UP             fe80::240b:70ff:fef6:5515/64 
lxc9a253d2ab7a1@if76 UP             fe80::f089:2eff:fe8a:8ca/64 
lxcc4bf9cc3bef6@if78 UP             fe80::586f:77ff:fe0c:8b85/64 
ovs-system       DOWN           
br-int           DOWN           
br-ex            UNKNOWN        
lxcf35a1b3e8e59@if85 UP             fe80::54f9:f7ff:fe69:cf86/64 
```

```
sunbeam-multi-node-2:~$ sudo tcpdump -elnvv -i any tcp port 80
tcpdump: data link type LINUX_SLL2
tcpdump: listening on any, link-type LINUX_SLL2 (Linux cooked v2), snapshot length 262144 bytes
12:25:57.742234 cilium_vxlan Out ifindex 6 a2:60:ce:d7:95:58 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 64, id 1233, offset 0, flags [DF], proto TCP (6), length 60)
    10.1.1.127.48102 > 10.1.0.235.80: Flags [S], cksum 0x169a (incorrect -> 0x3c7f), seq 2647968659, win 64860, options [mss 1410,sackOK,TS val 3665950665 ecr 0,nop,wscale 7], length 0
12:26:00.210863 cilium_vxlan Out ifindex 6 a2:60:ce:d7:95:58 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 64, id 11780, offset 0, flags [DF], proto TCP (6), length 60)
    10.1.1.127.41796 > 10.1.0.235.80: Flags [S], cksum 0x169a (incorrect -> 0xb1cf), seq 2379183430, win 64860, options [mss 1410,sackOK,TS val 3665953133 ecr 0,nop,wscale 7], length 0
12:26:01.262237 cilium_vxlan Out ifindex 6 a2:60:ce:d7:95:58 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 64, id 11781, offset 0, flags [DF], proto TCP (6), length 60)
    10.1.1.127.41796 > 10.1.0.235.80: Flags [S], cksum 0x169a (incorrect -> 0xadb3), seq 2379183430, win 64860, options [mss 1410,sackOK,TS val 3665954185 ecr 0,nop,wscale 7], length 0
12:26:02.286258 cilium_vxlan Out ifindex 6 a2:60:ce:d7:95:58 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 64, id 11782, offset 0, flags [DF], proto TCP (6), length 60)
    10.1.1.127.41796 > 10.1.0.235.80: Flags [S], cksum 0x169a (incorrect -> 0xa9b3), seq 2379183430, win 64860, options [mss 1410,sackOK,TS val 3665955209 ecr 0,nop,wscale 7], length 0
12:26:03.310270 cilium_vxlan Out ifindex 6 a2:60:ce:d7:95:58 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 64, id 11783, offset 0, flags [DF], proto TCP (6), length 60)
    10.1.1.127.41796 > 10.1.0.235.80: Flags [S], cksum 0x169a (incorrect -> 0xa5b3), seq 2379183430, win 64860, options [mss 1410,sackOK,TS val 3665956233 ecr 0,nop,wscale 7], length 0
12:26:04.334253 cilium_vxlan Out ifindex 6 a2:60:ce:d7:95:58 ethertype IPv4 (0x0800), length 80: (tos 0x0, ttl 64, id 11784, offset 0, flags [DF], proto TCP (6), length 60)
    10.1.1.127.41796 > 10.1.0.235.80: Flags [S], cksum 0x169a (incorrect -> 0xa1b3), seq 2379183430, win 64860, options [mss 1410,sackOK,TS val 3665957257 ecr 0,nop,wscale 7], length 0
```

### What Should Happen Instead?

The second node addition should succeed by reaching to the Juju controller.

### Reproduction Steps

Follow the two tutorial articles:
- https://canonical-openstack.readthedocs-hosted.com/en/latest/how-to/install/install-canonical-openstack-using-the-manual-bare-metal-provider/
- https://canonical-openstack.readthedocs-hosted.com/en/latest/how-to/operations/scaling-the-cluster-out/

### System information

- [node-1_inspection-report-20250623_131108.tar.gz](https://github.com/user-attachments/files/20865833/node-1_inspection-report-20250623_131108.tar.gz)
- [node-2_inspection-report-20250623_131113.tar.gz](https://github.com/user-attachments/files/20865834/node-2_inspection-report-20250623_131113.tar.gz)

### Can you suggest a fix?

_No response_

### Are you interested in contributing with a fix?

_No response_

### PR DESCRIPTION
**Pull request by HomayoonAlimohammadi**
### Overview
This PR suggests a fix for the `cilium_vxlan` interface getting removed.

Fixes #1495 
Fixes #1585

### CODE REVIEW

File: src/k8s/pkg/k8sd/features/cilium/network.go [hunk 1]
```diff
@@ -37,22 +37,11 @@ func checkAndSanitizeCiliumVXLAN(port int) error {
...
-			// changes. Removing the interface before applying the new manifests is a temporary
-			// workaround. We can remove this block when the following issue gets settled:
-			// https://github.com/cilium/cilium/issues/38581
-			if err := utils.RemoveLink(vxlanDevice.Name); err != nil {
-				return err
-			}
-
-			continue
+		if vxlanDevice.Port == port && vxlanDevice.Name != ciliumVXLANDeviceName {
+			return fmt.Errorf("interface %s uses the same destination port as cilium. Please consider removing that device manually", vxlanDevice.Name)
```
Comment (rapour) [inline src/k8s/pkg/k8sd/features/cilium/network.go]: I think it's better to suggest changing the cilium port rather than removing an interface not controlled by k8s. That interface may be integral to the funtion of their environment. 
```suggestion
			return fmt.Errorf("interface %s uses the same destination port as cilium. Please consider changing the Cilium tunnel port", vxlanDevice.Name)
```

Comment (berkayoz) [reply src/k8s/pkg/k8sd/features/cilium/network.go]: +1 on this

File: src/k8s/pkg/k8sd/features/cilium/network.go [hunk 2]
```diff
@@ -37,22 +37,11 @@ func checkAndSanitizeCiliumVXLAN(port int) error {
...
 		}
-
-		if vxlanDevice.Port == port {
-			return fmt.Errorf("interface %s uses the same destination port as cilium", vxlanDevice.Name)
+		if vxlanDevice.Name == ciliumVXLANDeviceName && vxlanDevice.Port != port {
+			return fmt.Errorf("interface %s uses a different destination port (%d) than the provided config (%d). Please consider removing that device manually", vxlanDevice.Name, vxlanDevice.Port, port)
```
Comment (berkayoz) [inline src/k8s/pkg/k8sd/features/cilium/network.go]: This is fine as a check / message however I've bigger questions in terms of the usefulness of this. This check is only performed for the node feature controller is running at. For a multi-node cluster this doesn't work as expected, other nodes might still have the old `cilium_vxlan` interface which will result in Cilium pod failure.

I feel like it is better to point out the port is already in use and for the user to adjust their configuration. We should update our documentation to reflect that this interface removal operation should be performed manually on each node.

**Review by berkayoz — COMMENTED** [review]
LGTM overall, small comments

File: src/k8s/pkg/k8sd/features/cilium/network.go (hunk 2 above)
Comment (HomayoonAlimohammadi) [reply src/k8s/pkg/k8sd/features/cilium/network.go]: I changed the message to:
`Please consider adjusting the cluster configuration or removing that device manually`. Does this cut it? We can also create a card for the documentation side of things.

**Review by berkayoz — APPROVED** [review]
LGTM
